title: API Commodities
email: contato@ciag.org.br
description: >- # this means to ignore newlines until "baseurl:"
  This is a web site to describe how to work an OpenCIAg API of commodities.
baseurl: "" #/api-commodities the subpath of your site, e.g. /blog
url: "https://openciag.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  OpenCIAg

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
    values:
      author: CIAg
  -
    scope:
      type: "post"
      path: ""
    values:
      layout: "post"
  -
    scope:
      type: "page"
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "assets"
    values:
      asset: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
